// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVAQlmUbqjuj8ERmfuXqaFVWyYocAt1K4',
    appId: '1:1031170635381:web:47d1e7344e94a4ced06a3c',
    messagingSenderId: '1031170635381',
    projectId: 'pokedex-7e8d1',
    authDomain: 'pokedex-7e8d1.firebaseapp.com',
    storageBucket: 'pokedex-7e8d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJAOur34IfpTy7KK1395Hcya9I6fAA_BE',
    appId: '1:1031170635381:android:5db090267fed6139d06a3c',
    messagingSenderId: '1031170635381',
    projectId: 'pokedex-7e8d1',
    storageBucket: 'pokedex-7e8d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnU4e-Ukht7JkznDoiXhIAQisvncHZwmI',
    appId: '1:1031170635381:ios:e42aa97dff45e0e8d06a3c',
    messagingSenderId: '1031170635381',
    projectId: 'pokedex-7e8d1',
    storageBucket: 'pokedex-7e8d1.firebasestorage.app',
    iosBundleId: 'com.example.deltechChallenge',
  );
}
